language: scala
scala:
  - 2.13.5

jdk:
  - oraclejdk8

services:
  - postgresql
  - mysql
cache:
  directories:
    - vendor/bundle
    - $HOME/.m2
    - $HOME/.ivy2
    - $HOME/.sbt
before_script:
  - ./script/prepare_build.sh

notifications:
  email:
    - linhares.mauricio@gmail.com